// 365 frases diarias — una por cada día del año.
// Tema: latidos, tiempo, acción, honestidad, avanzar.

const QUOTES: string[] = [
  "Cada latido es una oportunidad de empezar de nuevo.",
  "No necesitas tenerlo todo claro. Solo dar el siguiente paso.",
  "Tu corazón ya lleva latiendo por ti antes de que decidieras actuar.",
  "Lo que evitas no desaparece. Late debajo de todo lo demás.",
  "Un latido honesto vale más que mil planes perfectos.",
  "Hoy tienes exactamente los latidos que necesitas para avanzar.",
  "El coraje no es no tener miedo. Es latir a pesar de él.",
  "No posponer es la forma más pura de respetarte.",
  "Cada decisión que tomas es un latido con dirección.",
  "Lo que haces hoy decide quién serás mañana.",
  "Tu ritmo no tiene que ser rápido. Solo tiene que ser tuyo.",
  "A veces el latido más valiente es pedir ayuda.",
  "No esperes a sentirte listo. Empieza desde donde estás.",
  "El bloqueo también es información. Escúchalo.",
  "Tres mil millones de latidos. ¿Cuántos vas a desperdiciar dudando?",
  "La claridad no llega pensando. Llega actuando.",
  "Un día sin acción es un día sin pulso.",
  "Lo importante rara vez es urgente. Pero siempre late.",
  "Tu ansiedad es energía sin dirección. Dale un destino.",
  "No necesitas motivación. Necesitas un primer movimiento.",
  "Cada latido te recuerda que sigues aquí. Úsalo.",
  "La perfección es la excusa favorita de la parálisis.",
  "Hoy no tienes que resolver todo. Solo lo que importa.",
  "El miedo al fracaso es el fracaso más silencioso.",
  "Tu corazón no deja de latir por las dudas. Tú tampoco deberías.",
  "Lo pequeño hecho hoy vale más que lo grande planeado para mañana.",
  "Avanzar con miedo sigue siendo avanzar.",
  "No hay latido insignificante cuando lo usas con intención.",
  "La duda es normal. Quedarse en ella, opcional.",
  "Cada mañana es un reset. Tu corazón ya lo sabe.",
  // Febrero
  "Lo que pospones te pesa más que lo que enfrentas.",
  "Tu ritmo de hoy no define tu capacidad de mañana.",
  "A veces latir es simplemente no rendirse.",
  "El primer paso no tiene que ser grande. Solo real.",
  "No compares tu ritmo con el de nadie.",
  "La honestidad contigo mismo es el latido más fuerte.",
  "Hoy puedes elegir: repetir o evolucionar.",
  "Cada excusa es un latido que usas contra ti.",
  "Lo difícil no es empezar. Es volver a empezar.",
  "Tu cuerpo late. Tu mente decide. Tu acción transforma.",
  "No necesitas el momento perfecto. Necesitas este momento.",
  "El cambio empieza en un latido. El tuyo. Ahora.",
  "Dejar de evitar es el primer acto de valentía.",
  "Lo que te frena suele ser más pequeño de lo que imaginas.",
  "Un latido consciente vale más que mil automáticos.",
  "Hoy tienes permiso para avanzar imperfectamente.",
  "El progreso no se ve día a día. Se siente latido a latido.",
  "Tu mejor versión no está en el futuro. Está en lo que haces ahora.",
  "La incomodidad es el precio de la transformación.",
  "Cada latido desperdiciado en preocupación es uno menos para crear.",
  "No tienes que ser valiente todo el día. Solo en este instante.",
  "Lo que importa no grita. Late.",
  "Tu historia la escribes con acciones, no con intenciones.",
  "Hoy es el día que tu yo del futuro necesitaba que empezaras.",
  "El silencio entre latidos también es parte del ritmo.",
  "Hacer algo mal es infinitamente mejor que no hacer nada.",
  "Tu ansiedad quiere que corras. Tu sabiduría quiere que avances.",
  "Cada latido es una segunda oportunidad disfrazada de rutina.",
  "No necesitas un plan. Necesitas un compromiso de 5 minutos.",
  "La acción cura lo que la reflexión sola no puede.",
  // Marzo
  "Latir es fácil. Vivir con intención, eso es el reto.",
  "Lo que hoy parece imposible, mañana será tu nueva normalidad.",
  "El miedo es un invitado. No tiene que ser el dueño.",
  "Tu corazón no negocia con la pereza. Tú tampoco deberías.",
  "El cambio real empieza cuando dejas de esperar permiso.",
  "Cada latido es una pregunta: ¿qué vas a hacer conmigo?",
  "No pidas motivación. Pide claridad.",
  "El hábito es más poderoso que la inspiración.",
  "Lo que no decides, alguien lo decide por ti.",
  "Tu cuerpo late sin pedirte opinión. Actúa con esa misma certeza.",
  "El bloqueo no es el problema. Es la señal.",
  "Mereces invertir en ti con la misma urgencia que inviertes en otros.",
  "La procrastinación es un diálogo contigo mismo que puedes cambiar.",
  "No hay atajo. Pero sí hay latidos bien usados.",
  "Hoy puedes hacer algo que mañana agradecerás.",
  "La vulnerabilidad no es debilidad. Es el latido más humano.",
  "Deja de planificar la vida que quieres. Empieza a latirla.",
  "El progreso invisible es el más real.",
  "Cada día es un lienzo de latidos. Pinta algo que importe.",
  "No busques la salida. Busca el siguiente paso.",
  "Tu resistencia es una historia que puedes reescribir.",
  "El coraje es hacer lo correcto cuando nadie te ve.",
  "Tres mil millones no son infinitos. Son tuyos. Úsalos.",
  "Hoy no tienes que ganar. Solo tienes que participar.",
  "La constancia late más fuerte que el talento.",
  "Lo que llamas fracaso, tu corazón lo llama práctica.",
  "No dejes que el cansancio decida tu futuro.",
  "Avanzar lento sigue siendo avanzar.",
  "Tu próximo latido puede ser el que cambie todo.",
  "El mejor momento para actuar fue ayer. El segundo mejor es ahora.",
  // Abril
  "Un latido con propósito es más poderoso que mil sin rumbo.",
  "Lo que evitas hoy será tu peso mañana.",
  "No necesitas entender todo para empezar a moverte.",
  "Tu corazón late sin excusas. Aprende de él.",
  "La claridad es un lujo. La acción, una necesidad.",
  "Cada latido que usas en quejarte es uno menos para construir.",
  "No te pido que seas perfecto. Te pido que seas honesto.",
  "El miedo a equivocarte es más dañino que el error.",
  "Hoy puedes elegir avanzar o puedes elegir quedarte igual.",
  "Lo que te asusta probablemente es lo que necesitas hacer.",
  "Tu ritmo importa. Tu dirección, más.",
  "No hay latidos de sobra. Todos cuentan.",
  "La única derrota real es dejar de intentar.",
  "Respira. Late. Actúa. Repite.",
  "Lo que postergas no espera. Crece.",
  "Tu mejor idea no vale nada sin ejecución.",
  "El cambio no avisa. Llega cuando decides latir diferente.",
  "Hoy tienes una cita contigo mismo. No faltes.",
  "La comodidad es el mayor obstáculo del crecimiento.",
  "No compitas con nadie. Supera tu latido de ayer.",
  "Cada decisión postergada es una decisión tomada: quedarte igual.",
  "Tu potencial no se mide en sueños. Se mide en acciones.",
  "El primer latido del día define los demás.",
  "No busques la perfección. Busca la consistencia.",
  "Lo que necesitas está al otro lado de lo que evitas.",
  "Un latido sin acción es solo ruido biológico.",
  "Deja de prepararte y empieza a hacer.",
  "Tu vida se cuenta en latidos. ¿Qué cuentan los de hoy?",
  "La disciplina es libertad disfrazada de esfuerzo.",
  "No necesitas suerte. Necesitas constancia.",
  "Cada latido es un voto por la persona que quieres ser.",
  // Mayo
  "Lo urgente rara vez es importante. Lo importante siempre late.",
  "Hoy es un buen día para hacer lo que llevas posponiendo.",
  "Tu corazón no procrastina. Es hora de que tú tampoco.",
  "La diferencia entre querer y tener es hacer.",
  "No esperes a que el miedo se vaya. Camina con él.",
  "El latido más fuerte es el que das cuando nadie te obliga.",
  "La rendición es silenciosa. El compromiso, ruidoso.",
  "Lo que construyes con constancia nadie te lo quita.",
  "Hoy puedes plantar la semilla que florecerá en un mes.",
  "Tu energía es finita. Inviértela donde importa.",
  "No todo lo que late es urgente. Pero todo lo urgente late.",
  "Equivocarte rápido es aprender rápido.",
  "El mejor plan es el que ejecutas hoy.",
  "Tu ansiedad no es tu enemiga. Es una alarma mal calibrada.",
  "Cada latido malgastado en duda es uno robado a la acción.",
  "Lo que te define no es lo que piensas. Es lo que haces.",
  "No te preguntes si puedes. Pregúntate si quieres.",
  "El silencio de la inacción es más ruidoso que cualquier error.",
  "Hoy tu corazón va a latir unas 100.000 veces. Haz que valgan.",
  "La paciencia sin acción es solo espera.",
  "No todo tiene que ser épico. A veces basta con ser constante.",
  "Tu próximo movimiento es más importante que tu último error.",
  "El hábito correcto hace innecesaria la motivación.",
  "Lo que resistes, persiste. Lo que enfrentas, se transforma.",
  "Un latido tras otro. Así se construye una vida.",
  "El cambio no es un evento. Es un latido diario.",
  "Tu futuro te lo agradecerá. Empieza ahora.",
  "La excusa más común es el tiempo. La verdad más común es el miedo.",
  "Cada día que pasa sin actuar, el cambio se hace más difícil.",
  "No te pido mucho. Te pido un latido honesto al día.",
  "La acción imperfecta siempre supera a la inacción perfecta.",
  // Junio
  "El verano del cambio empieza con un latido de decisión.",
  "No hay mejor momento que este. Literalmente este.",
  "Tu corazón late con o sin tu permiso. Tu vida requiere tu voluntad.",
  "Lo fácil te mantiene cómodo. Lo necesario te hace crecer.",
  "Cada día es una nueva posibilidad de hacerlo diferente.",
  "El arrepentimiento pesa más que el esfuerzo.",
  "No confundas pensar con avanzar.",
  "Hoy no tienes que ser extraordinario. Solo tienes que ser real.",
  "Lo que necesitas no es tiempo. Es prioridad.",
  "Tu ritmo cardíaco no negociable. Tu compromiso tampoco debería serlo.",
  "La distancia entre donde estás y donde quieres estar se mide en acciones.",
  "No dejes que la opinión de otros dicte tu ritmo.",
  "Cada latido es un recordatorio de que puedes empezar de nuevo.",
  "La grandeza está en los detalles que nadie ve.",
  "Hoy puedes cambiar un hábito. Solo uno. Es suficiente.",
  "Tu peor enemigo es la versión de ti que se conforma.",
  "No necesitas más información. Necesitas más ejecución.",
  "El latido de hoy es la base del logro de mañana.",
  "La transformación empieza cuando dejas de negociar contigo.",
  "Cada excusa tiene un latido que podría haberse usado mejor.",
  "Lo que importa de verdad no viene con instrucciones.",
  "Hoy, elige una cosa. Hazla. Sin más.",
  "La vida no espera a que estés listo. Late igual.",
  "Tu fortaleza se construye en los días que menos ganas tienes.",
  "No necesitas aprobación. Necesitas acción.",
  "El miedo es temporal. El arrepentimiento, permanente.",
  "Un día malo con acción es mejor que un día bueno sin ella.",
  "Tu corazón no se toma días libres. Inspírate en él.",
  "Lo que haces en silencio habla más fuerte que lo que dices.",
  "Cada latido es un sí a la vida. Cada acción es un sí a ti.",
  // Julio
  "El calor del verano no se compara con el fuego de la determinación.",
  "Hoy tienes 86.400 segundos. Usa al menos 300 en lo que importa.",
  "Lo que da miedo suele ser lo que más vale la pena.",
  "Tu latido es tu firma. Haz que sea legible.",
  "No busques inspiración. Crea las condiciones para que llegue.",
  "La mejor inversión es la que haces en ti, con cada latido.",
  "Hoy no tienes que correr. Solo no te pares.",
  "Lo que cuesta trabajo es lo que vale la pena recordar.",
  "Tu compromiso se mide en días consistentes, no en momentos brillantes.",
  "El cambio empieza cuando dices basta con amor propio.",
  "No hay atajo para lo que merece la pena.",
  "Cada latido es una moneda. ¿En qué la estás invirtiendo?",
  "La mediocridad es cómoda. La excelencia late diferente.",
  "Hoy puedes ser mejor que ayer. Solo un poco. Es suficiente.",
  "No te rindas. Tu próximo latido puede ser el que cambie el rumbo.",
  "Lo que te frena no es el obstáculo. Es la historia que te cuentas.",
  "Un paso real vale más que cien imaginarios.",
  "Tu cuerpo sabe latir. Tu mente necesita aprender a no estorbar.",
  "La única opinión que necesitas validar es la tuya, con acciones.",
  "Cada amanecer es un latido nuevo. Trátalo como tal.",
  "No pidas menos problemas. Pide más fuerza para resolverlos.",
  "Hoy es un buen día para romper un patrón.",
  "El hábito no pide permiso. Se instala con repetición.",
  "Lo que no mides no mejora. Lo que no haces no existe.",
  "Tu potencial sin acción es solo fantasía.",
  "La disciplina de hoy es la libertad de mañana.",
  "No tienes que sentirte motivado. Tienes que sentirte comprometido.",
  "Cada latido bien usado es un ladrillo de la vida que quieres.",
  "Lo que evitas decir se convierte en lo que evitas hacer.",
  "Hoy, hazlo mal. Mañana, hazlo mejor. Nunca dejes de hacerlo.",
  "Tu ritmo es único. No dejes que nadie lo silencie.",
  // Agosto
  "El descanso es parte del ritmo. No confundas pausar con parar.",
  "Hoy puedes elegir: ser espectador o protagonista.",
  "Lo que construyes con esfuerzo tiene cimientos que no se mueven.",
  "Cada latido es una declaración: sigo aquí.",
  "No esperes la tormenta perfecta. Navega con la brisa que hay.",
  "Tu mejor trabajo nace cuando dejas de buscar excusas.",
  "La paciencia activa es la forma más inteligente de latir.",
  "Hoy no necesitas todo. Necesitas algo. Empieza por ahí.",
  "Lo que te incomoda es tu próximo nivel.",
  "No hay latido desperdiciado si aprendes algo de él.",
  "Tu presente lo estás construyendo tu pasado reciente.",
  "La intensidad sin dirección es agotamiento. Con dirección, es poder.",
  "Hoy, permítete avanzar sin tener todas las respuestas.",
  "Lo que resistes internamente se manifiesta externamente.",
  "Cada latido es un pacto con tu futuro.",
  "No busques la perfección. Busca el progreso.",
  "La diferencia entre un sueño y un plan es una fecha.",
  "Tu energía fluye donde pones tu atención.",
  "Hoy puedes hacer una cosa que te asuste. Solo una.",
  "Lo que parece imposible hoy será tu historia de superación.",
  "No dejes que lo bueno sea enemigo de lo mejor.",
  "Cada latido te acerca o te aleja de quien quieres ser.",
  "La constancia no es glamurosa. Pero es imbatible.",
  "Hoy tu corazón ya hizo su parte. ¿Y tú?",
  "Lo que no te reta no te cambia.",
  "La claridad viene de la acción, no de la contemplación.",
  "Tu compromiso de hoy es el cimiento del logro de mañana.",
  "No todo latido tiene que ser perfecto. Solo tiene que ser real.",
  "Haz lo necesario. Luego lo posible. De pronto harás lo imposible.",
  "El mayor riesgo es no arriesgar nada.",
  "La vida se mide en latidos vividos, no en latidos contados.",
  // Septiembre
  "Septiembre es el enero real. Empieza de nuevo.",
  "Tu ritmo se renueva con cada decisión consciente.",
  "Lo que cultivas en silencio florece en público.",
  "Hoy, sé la persona que necesitabas ayer.",
  "Cada latido de otoño es una hoja que cae y una raíz que crece.",
  "No necesitas un nuevo comienzo. Necesitas un nuevo compromiso.",
  "Lo que haces cuando nadie te ve define quién eres.",
  "La transformación no es ruidosa. Late bajo la superficie.",
  "Hoy puedes soltar algo que ya no te sirve.",
  "El cambio de estación te recuerda: nada permanece igual.",
  "Tu mejor inversión es el primer latido de la mañana dedicado a ti.",
  "No te preguntes qué puede salir mal. Pregúntate qué puede salir bien.",
  "Cada rutina es un latido repetido. Elige rutinas que te construyan.",
  "La fuerza no es no caer. Es volver a latir después de cada caída.",
  "Hoy, elige profundidad sobre velocidad.",
  "Lo que te define es lo que haces cuando no tienes ganas.",
  "El latido más importante es el que das después de querer parar.",
  "No acumules días. Acumula acciones que importen.",
  "Tu cuerpo late automáticamente. Tu propósito requiere intención.",
  "Cada latido desperdiciado en comparación es uno robado a tu camino.",
  "La autenticidad es el latido más difícil y el más valioso.",
  "Hoy puedes perdonarte y empezar limpio.",
  "Lo que pides al universo, el universo te lo pide a ti en acción.",
  "El mejor consejo es el que ya sabes pero no aplicas.",
  "Tu latido de hoy es el eco que escucharás en un año.",
  "No esperes condiciones ideales. Crea las posibles.",
  "La gratitud es el latido que multiplica todo lo demás.",
  "Hoy, menos ruido y más ritmo.",
  "Cada paso cuenta. Incluso los que no se ven.",
  "Tu historia no la escribe el destino. La escribes tú, latido a latido.",
  // Octubre
  "Octubre te recuerda: lo que no cosechas, no lo plantaste.",
  "Hoy puedes ser sincero contigo mismo. Es gratis y transforma.",
  "Lo que late bajo tu resistencia es lo que más necesitas explorar.",
  "No confundas estar ocupado con estar avanzando.",
  "Cada latido en otoño te prepara para el invierno que viene.",
  "La acción te enseña más que cualquier libro.",
  "Hoy, prioriza lo esencial. Elimina lo decorativo.",
  "Tu corazón no distingue entre días buenos y malos. Late igual.",
  "La consistencia te lleva donde la motivación no puede.",
  "Lo que ignoras no desaparece. Se transforma en urgencia.",
  "Cada error es un latido invertido en aprendizaje.",
  "No te juzgues por el ritmo. Júzgate por la dirección.",
  "Hoy, un latido más hacia lo que importa.",
  "La prisa mata la calidad. El ritmo la perfecciona.",
  "Tu único competidor real eres tú ayer.",
  "Lo que te limita muchas veces es invisible. Nómbralo.",
  "Cada latido tiene el potencial de ser el principio de algo.",
  "No te aferres al resultado. Aférrate al proceso.",
  "La vida recompensa al que late con intención.",
  "Hoy puedes elegir el esfuerzo sobre la queja.",
  "Lo que haces repetidamente se convierte en lo que eres.",
  "Tu corazón late con constancia. Tu vida necesita lo mismo.",
  "Cada decisión es un latido con consecuencias.",
  "No busques el camino fácil. Busca el que te hace crecer.",
  "La sencillez es el latido más elegante.",
  "Hoy, haz espacio para lo que importa eliminando lo que no.",
  "El silencio interno es donde nacen los mejores latidos.",
  "Lo que te cuesta es lo que te forma.",
  "Cada latido es una prueba de que mereces estar aquí.",
  "No dejes que el ruido externo ahogue tu ritmo interno.",
  "Hoy es el único día que tienes garantizado. Úsalo.",
  // Noviembre
  "Noviembre te pide honestidad: ¿dónde estás de verdad?",
  "Cada latido en la quietud del otoño resuena más fuerte.",
  "Lo que no resuelves en noviembre, te acompañará en diciembre.",
  "Hoy, agradece un latido y actúa sobre otro.",
  "Tu fortaleza se prueba en la oscuridad, no en la luz.",
  "Lo que parece un final es muchas veces un latido de transición.",
  "Cada día más corto te recuerda: el tiempo no sobra.",
  "No esperes a diciembre para hacer balance. Hazlo ahora.",
  "Tu ritmo se ajusta, no se rompe.",
  "Lo que siembras en noviembre florece cuando menos lo esperas.",
  "Hoy, un acto de valentía silenciosa.",
  "La reflexión sin acción es solo rumia. Añade un paso.",
  "Cada latido te acerca a quien puedes ser.",
  "No te conformes con sobrevivir. Elige latir con propósito.",
  "Lo que te frena ahora será tu historia de superación.",
  "Hoy puedes ser amable contigo y exigente con tus excusas.",
  "El frío exterior no tiene que congelar tu determinación.",
  "Cada latido en silencio construye la base del ruido que viene.",
  "No midas tu valor en resultados. Mídelo en intentos.",
  "La perseverancia no es glamurosa. Pero es la que gana.",
  "Hoy, dale a tu latido una razón para ser recordado.",
  "Lo que niegas controla tu vida. Lo que aceptas, lo liberas.",
  "Cada paso en la oscuridad te acerca a la luz.",
  "No necesitas todo resuelto. Necesitas un paso resuelto.",
  "Tu latido es la única constante en un mundo de variables.",
  "Hoy, elige coraje sobre comodidad.",
  "Lo que te define no es lo que sientes. Es lo que haces con lo que sientes.",
  "Cada latido es un acto de fe en el futuro.",
  "La vulnerabilidad es el latido que conecta con los demás.",
  "El invierno que viene será más cálido si actúas ahora.",
  // Diciembre
  "Diciembre no es para cerrar. Es para latir con todo.",
  "Cada latido de diciembre es un resumen del año.",
  "Lo que no hiciste este año puede empezar hoy.",
  "Hoy, celebra lo que sí lograste. Aunque sea poco.",
  "Tu corazón no hace balance anual. Late día a día. Haz lo mismo.",
  "Lo que queda del año es suficiente para un cambio real.",
  "Cada latido en diciembre lleva el peso de la gratitud.",
  "No te pido que cambies el mundo. Solo tu próxima hora.",
  "El año que termina fue un latido largo. ¿Qué aprendiste?",
  "Hoy puedes perdonar y seguir. El rencor pesa más que la acción.",
  "Cada final es un latido que prepara el siguiente inicio.",
  "Lo que llevas dentro es más grande que cualquier obstáculo.",
  "Tu latido de diciembre tiene la sabiduría de 11 meses.",
  "No esperes enero. El cambio no entiende de calendarios.",
  "Cada día que queda es un regalo. No lo guardes. Úsalo.",
  "Lo que hiciste bien este año, repítelo. Lo que no, suéltalo.",
  "Tu corazón no necesita año nuevo para latir diferente.",
  "Hoy, agradece lo que tienes mientras trabajas por lo que quieres.",
  "Cada latido de fin de año es un puente hacia quien serás.",
  "No cierres el año con listas. Ciérralo con un compromiso.",
  "Lo que empieza con un latido honesto, termina bien.",
  "Tu mejor regalo de fin de año es la acción que llevas posponiendo.",
  "Cada segundo de diciembre es tiempo para ser mejor.",
  "No es tarde. Mientras latas, tienes tiempo.",
  "Hoy, el último latido del día puede ser el primero de tu cambio.",
  "El próximo año será diferente solo si tú lates diferente.",
  "Cada final de año es una invitación a empezar.",
  "Tu corazón no se despide del año. Transiciona. Haz lo mismo.",
  "Lo que te espera el año que viene depende de este latido.",
  "Tres mil millones de latidos. Hoy usaste uno bien. Es suficiente.",
  "El último latido del año es el primero del siguiente.",
];

/**
 * Returns the quote for today based on the day of the year.
 */
export function getDailyQuote(): string {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime();
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24));
  return QUOTES[dayOfYear % QUOTES.length];
}

export function getQuoteByIndex(index: number): string {
  return QUOTES[((index % QUOTES.length) + QUOTES.length) % QUOTES.length];
}
