import { type NextRequest, NextResponse } from "next/server";
import { requireAdminPermission } from "@/lib/admin-auth";
import { getPrismaClient } from "@/db/prisma";
import { logError } from "@/lib/logger";

export const dynamic = "force-dynamic";

// GET /api/admin/community/reflections?status=pending|published|all
// Pending = generated by LLM but not approved by admin yet — these are the
// ones that need review before being shown to the user.
export async function GET(req: NextRequest) {
  const auth = requireAdminPermission(req, "operations");
  if (auth instanceof NextResponse) return auth;

  try {
    const status = req.nextUrl.searchParams.get("status") ?? "pending";
    const where =
      status === "published"
        ? { publishedAt: { not: null } }
        : status === "all"
          ? {}
          : { publishedAt: null, approvedAt: null };

    const prisma = getPrismaClient();
    const reflections = await prisma.mentorReflection.findMany({
      where,
      orderBy: { generatedAt: "desc" },
      take: 100,
      select: {
        id: true,
        content: true,
        source: true,
        generatedAt: true,
        approvedAt: true,
        publishedAt: true,
        readAt: true,
        userId: true,
        user: { select: { email: true, name: true } },
        pulse: {
          select: {
            id: true,
            prompt: true,
            weekStart: true,
            circle: { select: { id: true, name: true, matchPattern: true, matchEmotion: true } },
          },
        },
      },
    });

    return NextResponse.json({
      reflections: reflections.map((r) => ({
        id: r.id,
        content: r.content,
        source: r.source,
        generatedAt: r.generatedAt.toISOString(),
        approvedAt: r.approvedAt?.toISOString() ?? null,
        publishedAt: r.publishedAt?.toISOString() ?? null,
        readAt: r.readAt?.toISOString() ?? null,
        userId: r.userId,
        userEmail: r.user.email,
        userName: r.user.name,
        pulseId: r.pulse.id,
        prompt: r.pulse.prompt,
        weekStart: r.pulse.weekStart.toISOString(),
        circleId: r.pulse.circle.id,
        circleName: r.pulse.circle.name,
        matchPattern: r.pulse.circle.matchPattern,
        matchEmotion: r.pulse.circle.matchEmotion,
      })),
    });
  } catch (error) {
    logError("ADMIN_REFLECTIONS", error, { route: "/api/admin/community/reflections" });
    return NextResponse.json({ error: "LOAD_FAILED" }, { status: 500 });
  }
}
